### ISSUE TITLE
Get pixel-wise output

### ISSUE THREAD

**Issue by STSpencer** [sstcam/sstcam_nsb#2]
We need to find a way of using ctapipe to convert from all-sky maps to pixel-wise values. This issue is to discuss how to handle this.

- [x] First step: Observe same field in camera plane using ctapipe, example here: https://cta-observatory.github.io/ctapipe/tutorials/coordinates_example.html?highlight=fov

**Comment by watsonjj** [comment]
Relavant sources:
https://github.com/watsonjj/sstcam-sandbox/blob/master/sstcam_sandbox/d190607_pointing/engineeringv2.ipynb
https://github.com/cta-observatory/ctapipe/pull/1085#issuecomment-499975961

**Comment by STSpencer** [comment]
Thanks, I'll take a look

**Comment by STSpencer** [comment]
I'm reasonably sure given the latest polaris runs that this issue can be considered closed, and the pixel values produced are at least reliable as relative intensities. There are still issues to consider regarding pixel extraction (particularly parameter selection) but they have separate issues.
